/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import java.awt.Graphics;  
import java.awt.Image;  
import java.awt.Toolkit;  
import javax.swing.JPanel;
public class First_Loging extends javax.swing.JFrame {

    /**
     * Creates new form First_Loging
     */
    public First_Loging() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        lblsystem = new javax.swing.JLabel();
        btndpt = new javax.swing.JButton();
        btnDg1 = new javax.swing.JButton();
        btnfao = new javax.swing.JButton();
        lblselect = new javax.swing.JLabel();
        jPanel1 =  new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    First_Loging.class.getResource("/Images/aathik.png"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };  ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        lblname.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblname.setText("Rice Cultivation Managment ");

        lblsystem.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblsystem.setText("System");

        btndpt.setBackground(new java.awt.Color(153, 153, 153));
        btndpt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndpt.setText("Department Agriculture Officer ");
        btndpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndptActionPerformed(evt);
            }
        });

        btnDg1.setBackground(new java.awt.Color(153, 153, 153));
        btnDg1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDg1.setText("Director General of Agriculture ");
        btnDg1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDg1ActionPerformed(evt);
            }
        });

        btnfao.setBackground(new java.awt.Color(153, 153, 153));
        btnfao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnfao.setText("Field Agriculture Officer ");
        btnfao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnfao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfaoActionPerformed(evt);
            }
        });

        lblselect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblselect.setText("Select user : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblname)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btndpt)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblselect)
                                .addComponent(btnDg1)))
                        .addGap(31, 31, 31))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblsystem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnfao)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsystem)
                .addGap(26, 26, 26)
                .addComponent(lblselect)
                .addGap(29, 29, 29)
                .addComponent(btnDg1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndpt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnfao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 300, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndptActionPerformed
        // TODO add your handling code here:
        {
              DAO dao=new DAO();
                dao.show();
                this.dispose();
    }
        
    }//GEN-LAST:event_btndptActionPerformed

    private void btnDg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDg1ActionPerformed
        // TODO add your handling code here:
        {
                DirectorGeneral dg=new DirectorGeneral();
                dg.show();
                this.dispose();
    }

    }//GEN-LAST:event_btnDg1ActionPerformed

    private void btnfaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfaoActionPerformed
        // TODO add your handling code here:
         Fireld_agri_officer fao=new Fireld_agri_officer();
                fao.show();
                this.dispose();
    }//GEN-LAST:event_btnfaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First_Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First_Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First_Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First_Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First_Loging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDg1;
    private javax.swing.JButton btndpt;
    private javax.swing.JButton btnfao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblselect;
    private javax.swing.JLabel lblsystem;
    // End of variables declaration//GEN-END:variables
}
